import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Money Command",
  description: "How Money Command collects, uses, and protects your personal and financial data.",
};

const LAST_UPDATED = "July 5, 2026";

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:py-14">
      <p className="text-sm font-medium text-indigo-600">Legal</p>
      <h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">Privacy Policy</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: {LAST_UPDATED}</p>

      <div className="prose prose-slate mt-8 max-w-none prose-headings:scroll-mt-20 prose-a:text-indigo-600">
        <p>
          Money Command (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is a personal finance web
          application operated by ForgePS. This Privacy Policy explains how we collect, use, store,
          and share information when you use Money Command at our website and related services
          (collectively, the &quot;Service&quot;).
        </p>

        <h2>Information we collect</h2>
        <ul>
          <li>
            <strong>Account information:</strong> email address and authentication identifiers when
            you create an account or sign in (via Firebase Authentication).
          </li>
          <li>
            <strong>Financial data you enter or sync:</strong> account names and balances,
            transactions, budgets, envelopes, goals, pay schedules, and planning data you add in the
            app.
          </li>
          <li>
            <strong>Bank connection data (optional):</strong> if you choose to link a financial
            institution through Plaid, we receive account and transaction data made available by
            Plaid and your institution. We do not receive or store your online banking password.
          </li>
          <li>
            <strong>Household sharing:</strong> if you join or invite others to a shared household,
            members of that household can access the financial data stored in that workspace.
          </li>
          <li>
            <strong>Technical data:</strong> standard server and hosting logs (for example, request
            timestamps and error diagnostics) generated by our hosting provider.
          </li>
        </ul>

        <h2>How we use information</h2>
        <p>We use your information to:</p>
        <ul>
          <li>Provide and maintain the Service (dashboards, budgets, envelopes, planning, etc.)</li>
          <li>Authenticate you and keep your workspace isolated from other users</li>
          <li>Sync linked bank accounts and transactions when you enable bank linking</li>
          <li>Improve reliability, security, and support</li>
          <li>Comply with legal obligations</li>
        </ul>
        <p>
          We do <strong>not</strong> sell your personal information. We do not use your financial
          data for advertising.
        </p>

        <h2>How data is stored</h2>
        <p>
          Your data is stored in Google Cloud / Firebase (project: personal-finance-ed108),
          including Firestore for application data. Authentication is handled by Firebase Auth.
          Session cookies are used to keep you signed in securely.
        </p>
        <p>
          Each user or household has a separate workspace. We design the Service so your data is
          scoped to your tenant and not mixed with other customers&apos; data.
        </p>

        <h2>Third-party services</h2>
        <ul>
          <li>
            <strong>Firebase / Google Cloud</strong> — hosting, authentication, and database. See{" "}
            <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer">
              Firebase Privacy
            </a>
            .
          </li>
          <li>
            <strong>Plaid</strong> — optional bank account linking and transaction import. Plaid&apos;s
            use of your data is also governed by{" "}
            <a href="https://plaid.com/legal/#end-user-privacy-policy" target="_blank" rel="noopener noreferrer">
              Plaid&apos;s End User Privacy Policy
            </a>
            . You can disconnect linked institutions in Settings.
          </li>
        </ul>

        <h2>Data retention and deletion</h2>
        <p>
          We retain your data while your account is active and as needed to provide the Service.
          You may request deletion of your account and associated data by contacting us (see
          Contact below). If you disconnect a bank via Plaid, we stop receiving new transaction
          data from that institution; previously imported data may remain until you delete it or
          your account.
        </p>

        <h2>Security</h2>
        <p>
          We use industry-standard measures including encrypted connections (HTTPS), authenticated
          API access, tenant-scoped data storage, and secret management for sensitive credentials.
          No method of transmission or storage is 100% secure; we cannot guarantee absolute
          security.
        </p>

        <h2>Your choices</h2>
        <ul>
          <li>Access and update financial data directly in the app</li>
          <li>Disconnect bank linking in Settings</li>
          <li>Sign out at any time from the sidebar</li>
          <li>Request account or data deletion by email</li>
        </ul>

        <h2>Children</h2>
        <p>
          The Service is not intended for users under 18. We do not knowingly collect information
          from children.
        </p>

        <h2>Changes to this policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will post the revised policy on
          this page and update the &quot;Last updated&quot; date.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about this Privacy Policy or your data:{" "}
          <a href="mailto:privacy@forgeps.com">privacy@forgeps.com</a>
        </p>
      </div>

      <div className="mt-10 flex flex-wrap gap-4 border-t border-slate-200 pt-6 text-sm">
        <Link href="/login" className="font-medium text-indigo-600 hover:text-indigo-500">
          Sign in
        </Link>
        <Link href="/" className="font-medium text-slate-600 hover:text-slate-900">
          Back to app
        </Link>
      </div>
    </div>
  );
}
